project_id = "kcehwcqdoxvkqakdvhsb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-badge]
    verify_jwt = false
  [functions.google-maps-proxy]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-booking-confirmation]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.create-connect-account]
    verify_jwt = false
  [functions.manage-coupons]
    verify_jwt = false
  [functions.validate-coupon]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-mesa]
    verify_jwt = false
  [functions.mesa-ai-assist]
    verify_jwt = false
  [functions.mesa-ai-cover]
    verify_jwt = false
