apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mesa-secrets
  namespace: mesa-prod
spec:
  encryptedData:
    DATABASE_URL: AgA...
    SUPABASE_URL: AgA...
    SUPABASE_ANON_KEY: AgA...
    SUPABASE_SERVICE_ROLE_KEY: AgA...
    JWT_SECRET: AgA...
    CLOUDFLARE_API_TOKEN: AgA...
  template:
    metadata:
      name: mesa-secrets
      namespace: mesa-prod
    type: Opaque
