// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined') return localStorage.getItem(key);
    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined') localStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    if (typeof window !== 'undefined') localStorage.removeItem(key);
  },
};

let _supabase: any = null;

function getSupabaseClient() {
  if (!_supabase) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key =
      process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    
    if (!url || !key) {
      console.warn('Supabase credentials not configured. Client initialization deferred.');
      return null;
    }
    
    _supabase = createClient<Database>(url, key, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
  return _supabase;
}

const noop = () => Promise.resolve({ data: { session: null }, error: null });
const noopSync = () => ({ data: { session: null }, error: null });

const mockClient = {
  auth: {
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
    getSession: noop,
    signOut: noop,
    signInWithOAuth: () => Promise.resolve({ data: null, error: null }),
  },
  from: (_table: string) => ({
    select: () => ({ data: null, error: null }),
    insert: () => ({ data: null, error: null }),
    update: () => ({ data: null, error: null }),
    delete: () => ({ data: null, error: null }),
  }),
  channel: () => ({
    on: () => ({ subscribe: () => {}, unsubscribe: () => {} }),
    subscribe: () => {},
  }),
  rpc: () => Promise.resolve({ data: null, error: null }),
};

export const supabase = new Proxy({}, {
  get: (_, prop: string | symbol) => {
    if (prop === '__skipDynamic') return true;
    const client = getSupabaseClient();
    if (!client) {
      return (mockClient as any)[prop];
    }
    return (client as any)[prop];
  }
}) as any;
