apiVersion: v1
kind: Service
metadata:
  name: mesa-web
  labels:
    app.kubernetes.io/name: mesa-web
    app.kubernetes.io/part-of: mesa-conecta-game
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mesa-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
