---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: mesa-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBxtGdt35uFSpIgBUb9U0PQosas8Fscviok4uwOa8BUj14BntMzkqnn2fGIgdqC3p4iCrmUrn3aegr0iQ6xi/3xAHAeU5YxasP2NALrYEkliAluptCIExniVwbWlcTcThUZpyzK/Pk8/BLQH1LZhhb6XKN/sJ6P7ycW/9GP9tevf1M3/Yid4+so5pH8/0Vs/RlXTZC/60BUvT09+Yn/jLHp3mMphORV1e4S3xD/AbFUnV2KbyKveOpiUz7nGEIg8dWifG9ucYd7onGoERLW6/Li7FtqnJ+NNRTD0u2ucr9ANnEvHdQB7c2ZgkW57EXvSPobjV9EQGy1+2P6x6JSo6w4NoFwKakfEkCuhSiwgiSLlibAThQxYV+3O4ARqY5E8nhSlOIEsDf0wqQ9HBRJWEkxVITBlSHCEQ7yqUeBOqzclriB3GX9F0VDz7xmnvDmucvTmoHE5d5KJiJ/3g56eRDZz6cFYSSewhBM5Iyysm8CXZ1B0j0u9kufe6JGc04z0S3I3go7QM0BT/C57HW9aabHaxzpI6tuOJLAq/QjaVsIJKnxJ6HIUmxnXasEoFFo5fjBUppkbHDBUMPdAkMTmSX16CVzENLEcP6D3WR/Vv/cXrGsY7cJpKbk5fftH5B7ylLuK7DqdGU9xq3+ar4OgZJAZofZ0z4v5NetO9+V/MtGuEIeEym8/zGlOpmJmkEOtR8KfRyYCHQset4XOWFJ1Tg4bDGU0DLKbOjf5PUc9AtAY2IwSNOUIkLIt1fd63QL0iJOgl0vY6+aMJaW31B/PdsXBDuwpRs4zFzgVqdVV8f3NZVGEEPpr40gN9R2uBxGZ8LWzZOYtOn5470FDtHLMbpNScGI1kVIaR4rjhCGC3TdNpnQsdO2fegorFgq+GHiAFxe8vHm2XaPwAwUcquV4BYzW8xWal64Os28Yc3ntih7cNuSlFGg113CblmEfFaPw1lF2AG2RcWLkg==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: mesa-dev
    type: kubernetes.io/dockerconfigjson
