apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesa-web-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: mesa-web
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BrunoBDevOceanoAzul/mesa-conecta-game.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: mesa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
