apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesa
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret-template.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
images:
  - name: ghcr.io/brunobdevoceanoazul/mesa-conecta-game/mesa-web
    newTag: latest
