apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mesa-web-secrets
  labels:
    app.kubernetes.io/name: mesa-web
spec:
  encryptedData:
    VITE_SUPABASE_URL: replace-with-kubeseal-output
    VITE_SUPABASE_PUBLISHABLE_KEY: replace-with-kubeseal-output
  template:
    metadata:
      name: mesa-web-secrets
      labels:
        app.kubernetes.io/name: mesa-web
    type: Opaque
