apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mesa-web
  labels:
    app.kubernetes.io/name: mesa-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mesa-web
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
