apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesa
resources:
  - namespace.yaml
  - configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/brunobdevoceanoazul/mesa-conecta-game/mesa-web
    newTag: latest
  - name: ghcr.io/brunobdevoceanoazul/mesa-conecta-game/mesa-api
    newTag: latest
