apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesa-dev
namePrefix: dev-
resources:
  - ../../base
  - sealed-secret.yaml
patches:
  - path: patch-deployment.yaml
images:
  - name: mesa-web
    newName: ghcr.io/brunobdevoceanoazul/mesa-conecta-game/mesa-web
    newTag: develop
  - name: mesa-api
    newName: ghcr.io/brunobdevoceanoazul/mesa-conecta-game/mesa-api
    newTag: develop
